@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "nc.unc.ktrochon.pocketlist.repository.ListRepository#ListRepository(Context)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.repository.ListRepository",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1408166297 { 
   	label=ListRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   ListRepository886306589XXXListRepository1678783089[
	label="+ ListRepository()"
	style=filled
	fillcolor=white
	tooltip="ListRepository

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1943718057 { 
   	label=DetailsProduitActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   DetailsProduitActivity1243990011XXXsauvegarderProduit2666181[
	label="+ sauvegarderProduit()"
	style=filled
	fillcolor=white
	tooltip="DetailsProduitActivity

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_407810375 { 
   	label=ListProduitDetailsActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   ListProduitDetailsActivity1243990011XXXsauvegarderListe2666181[
	label="+ sauvegarderListe()"
	style=filled
	fillcolor=white
	tooltip="ListProduitDetailsActivity

null"
	fontcolor=darkgreen
];

ListProduitDetailsActivity1243990011XXXsupprimerListe2666181[
	label="+ supprimerListe()"
	style=filled
	fillcolor=white
	tooltip="ListProduitDetailsActivity

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_836149784 { 
   	label=ListServices
	labeljust=l
	fillcolor=white
	style=filled
   
   ListServices121729986XXXdeleteList1642869784[
	label="+ deleteList()"
	style=filled
	fillcolor=white
	tooltip="ListServices

null"
	fontcolor=darkgreen
];

ListServices121729986XXXgetAllList1678783089[
	label="+ getAllList()"
	style=filled
	fillcolor=white
	tooltip="ListServices

null"
	fontcolor=darkgreen
];

ListServices121729986XXXgetListProduitByName406701772[
	label="+ getListProduitByName()"
	style=filled
	fillcolor=white
	tooltip="ListServices

null"
	fontcolor=darkgreen
];

ListServices121729986XXXmiseAJourListProduit1999450483[
	label="+ miseAJourListProduit()"
	style=filled
	fillcolor=white
	tooltip="ListServices

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ListServices121729986XXXgetListProduitByName406701772;
ListProduitDetailsActivity1243990011XXXsauvegarderListe2666181 -> ListServices121729986XXXgetListProduitByName406701772;
ListProduitDetailsActivity1243990011XXXsauvegarderListe2666181 -> ListServices121729986XXXmiseAJourListProduit1999450483;
ListProduitDetailsActivity1243990011XXXsupprimerListe2666181 -> ListServices121729986XXXdeleteList1642869784;
ListProduitDetailsActivity1243990011XXXsupprimerListe2666181 -> ListServices121729986XXXgetListProduitByName406701772;
ListServices121729986XXXdeleteList1642869784 -> ListRepository886306589XXXListRepository1678783089;
ListServices121729986XXXgetAllList1678783089 -> ListRepository886306589XXXListRepository1678783089;
ListServices121729986XXXgetListProduitByName406701772 -> ListRepository886306589XXXListRepository1678783089;
ListServices121729986XXXmiseAJourListProduit1999450483 -> ListRepository886306589XXXListRepository1678783089;
    
}
@enduml