@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "nc.unc.ktrochon.pocketlist.DetailsProduitActivity#sauvegarderProduit(View)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.DetailsProduitActivity",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1408166297 { 
   	label=ListRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   ListRepository886306589XXXgetListesProduitByName1808118735[
	label="+ getListesProduitByName()"
	style=filled
	fillcolor=white
	tooltip="ListRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1943718057 { 
   	label=DetailsProduitActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   DetailsProduitActivity1243990011XXXsauvegarderProduit2666181[
	label="+ sauvegarderProduit()"
	style=filled
	fillcolor=white
	tooltip="DetailsProduitActivity

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_596400111 { 
   	label=AppartenirRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   AppartenirRepository886306589XXXaddAppartenir1033387535[
	label="+ addAppartenir()"
	style=filled
	fillcolor=white
	tooltip="AppartenirRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_774926626 { 
   	label=ProduitRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   ProduitRepository886306589XXXaddProduit1355179401[
	label="+ addProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];

ProduitRepository886306589XXXgetProduitByName1808118735[
	label="+ getProduitByName()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];

ProduitRepository886306589XXXupdateNomProduit1897515218[
	label="+ updateNomProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_836149784 { 
   	label=ListServices
	labeljust=l
	fillcolor=white
	style=filled
   
   ListServices121729986XXXgetListProduitByName406701772[
	label="+ getListProduitByName()"
	style=filled
	fillcolor=white
	tooltip="ListServices

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_883855765 { 
   	label=AppartenirService
	labeljust=l
	fillcolor=white
	style=filled
   
   AppartenirService121729986XXXadd497076308[
	label="+ add()"
	style=filled
	fillcolor=white
	tooltip="AppartenirService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_908840667 { 
   	label=ProduitServices
	labeljust=l
	fillcolor=white
	style=filled
   
   ProduitServices121729986XXXaddProduit1849432294[
	label="+ addProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];

ProduitServices121729986XXXgetProduitByName406701772[
	label="+ getProduitByName()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];

ProduitServices121729986XXXmiseAJourNomProduit500514187[
	label="+ miseAJourNomProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AppartenirService121729986XXXadd497076308 -> AppartenirRepository886306589XXXaddAppartenir1033387535;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> AppartenirService121729986XXXadd497076308;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ListServices121729986XXXgetListProduitByName406701772;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ProduitServices121729986XXXaddProduit1849432294;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ProduitServices121729986XXXgetProduitByName406701772;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ProduitServices121729986XXXmiseAJourNomProduit500514187;
ListServices121729986XXXgetListProduitByName406701772 -> ListRepository886306589XXXgetListesProduitByName1808118735;
ProduitServices121729986XXXaddProduit1849432294 -> ProduitRepository886306589XXXaddProduit1355179401;
ProduitServices121729986XXXgetProduitByName406701772 -> ProduitRepository886306589XXXgetProduitByName1808118735;
ProduitServices121729986XXXmiseAJourNomProduit500514187 -> ProduitRepository886306589XXXupdateNomProduit1897515218;
    
}
@enduml