@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.ListProduitActivity",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Appartenir165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Appartenir</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   key_app: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   key_list: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   key_prod: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   quantite: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AppartenirRepository886306589[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AppartenirRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connexion: ListDAO [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   list: List&lt;Appartenir&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addAppartenir(numeroListe: int, numeroProduit: int, quantity: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deletedList(numeroListe: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deletedProductInList(numeroProduit: int, numeroListe: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAppartenanceByListe(numeroListe: int): List&lt;Appartenir&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAppartenirByListe(numeroListe: int, numeroProduit: int): Appartenir</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateProductList(numeroListe: int, numeroProduit: int, newNumeroProduit: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateQuantity(numeroListe: int, numeroProduit: int, newQuantity: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AppartenirService121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AppartenirService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   listServices: ListServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produitServices: ProduitServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: AppartenirRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ add(context: Context, numeroListe: int, numeroProduit: int, quantity: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteList(context: Context, numeroListe: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteProductInList(context: Context, numeroProduit: int, numeroListe: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllAppartenir(context: Context, numeroListe: int): List&lt;Appartenir&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAppartenir(context: Context, numeroListe: int, numeroProduit: int): Appartenir</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateProductInListe(context: Context, numeroListe: int, numeroProduit: int, nouveauNumeroProduit: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateQuantity(context: Context, numeroListe: int, numeroProduit: int, newQuantity: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CategoryProduit165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryProduit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   categoryId: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryName: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CategoryRepository886306589[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connexion: ListDAO [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getCategoryById(numeroCategory: int): CategoryProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCategoryByName(category: String): CategoryProduit</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CategoryServices121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryProduit: CategoryProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: CategoryRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getAllCategory(context: Context): List&lt;CategoryProduit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCategoryById(context: Context, id: int): CategoryProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCategoryProduitByName(context: Context, categoryName: String): CategoryProduit</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListDAO1311685889[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListDAO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCreate(db: SQLiteDatabase)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onUpgrade(db: SQLiteDatabase, i: int, i1: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProduit165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProduit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProduitActivity1243990011[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProduitActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   adapter: ProduitAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   appartenir: List&lt;Appartenir&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   category: List&lt;CategoryProduit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   caterogyServices: CategoryServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listProduit: ListProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listServices: ListServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produitServices: ProduitServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produits: List&lt;Produit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   services: AppartenirService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onClick(view: View)</TD></TR>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ showNoteDetail(produitIndex: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListRepository886306589[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connexion: ListDAO [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addListe(listProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteListe(listProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getListesProduitByName(name: String): ListProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateTitleList(listProduit: ListProduit, nom: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListServices121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   listProduit: ListProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: ListRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteList(context: Context, ListProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllList(context: Context): List&lt;ListProduit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getListProduitByName(context: Context, title: String): ListProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ miseAJourListProduit(context: Context, ListProduit: ListProduit, title: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Produit165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Produit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   category: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   categoryName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nomProduit: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProduitAdapter1282035804[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProduitAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   appartenirs: List&lt;Appartenir&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryProduits: List&lt;CategoryProduit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   itemClickListener: OnClickListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produits: List&lt;Produit&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(holder: ViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(parent: ViewGroup, viewType: int): ViewHolder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProduitRepository886306589[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProduitRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connexion: ListDAO [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addProduit(produit: Produit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteProduit(produit: Produit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllProduit(numeroList: int): List&lt;Produit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProduitByName(nomProduit: String): Produit</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateDescriptionProduit(produit: Produit, newDescription: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateNomProduit(produit: Produit, nom: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProduitServices121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProduitServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   produit: Produit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: ProduitRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addProduit(context: Context, produit: Produit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteProduit(context: Context, produit: Produit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAll(context: Context): List&lt;Produit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllProduit(context: Context, numeroListe: int): List&lt;Produit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProduitByName(context: Context, name: String): Produit</TD></TR>
<TR><TD ALIGN="LEFT" >+ miseAJourNomProduit(context: Context, produit: Produit, nomProduit: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateDescriptionProduct(context: Context, produit: Produit, newDescription: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AppartenirRepository886306589 -> Appartenir165667126[label="list
[0..*]"];
AppartenirRepository886306589 -> ListDAO1311685889[label="connexion
[0..1]"];
AppartenirService121729986 -> AppartenirRepository886306589[label="repository
[0..1]"];
AppartenirService121729986 -> ListServices121729986[label="listServices
[0..1]"];
AppartenirService121729986 -> ProduitServices121729986[label="produitServices
[0..1]"];
CategoryRepository886306589 -> ListDAO1311685889[label="connexion
[0..1]"];
CategoryServices121729986 -> CategoryProduit165667126[label="categoryProduit
[0..1]"];
CategoryServices121729986 -> CategoryRepository886306589[label="repository
[0..1]"];
ListProduitActivity1243990011 -> Appartenir165667126[label="appartenir
[0..*]"];
ListProduitActivity1243990011 -> AppartenirService121729986[label="services
[0..1]"];
ListProduitActivity1243990011 -> CategoryProduit165667126[label="category
[0..*]"];
ListProduitActivity1243990011 -> CategoryServices121729986[label="caterogyServices
[0..1]"];
ListProduitActivity1243990011 -> ListProduit165667126[label="listProduit
[0..1]"];
ListProduitActivity1243990011 -> ListServices121729986[label="listServices
[0..1]"];
ListProduitActivity1243990011 -> Produit165667126[label="produits
[0..*]"];
ListProduitActivity1243990011 -> ProduitAdapter1282035804[label="adapter
[0..1]"];
ListProduitActivity1243990011 -> ProduitServices121729986[label="produitServices
[0..1]"];
ListRepository886306589 -> ListDAO1311685889[label="connexion
[0..1]"];
ListServices121729986 -> ListProduit165667126[label="listProduit
[0..1]"];
ListServices121729986 -> ListRepository886306589[label="repository
[0..1]"];
ProduitAdapter1282035804 -> Appartenir165667126[label="appartenirs
[0..*]"];
ProduitAdapter1282035804 -> CategoryProduit165667126[label="categoryProduits
[0..*]"];
ProduitAdapter1282035804 -> Produit165667126[label="produits
[0..*]"];
ProduitRepository886306589 -> ListDAO1311685889[label="connexion
[0..1]"];
ProduitServices121729986 -> Produit165667126[label="produit
[0..1]"];
ProduitServices121729986 -> ProduitRepository886306589[label="repository
[0..1]"];
    
}
@enduml