@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.ListProduitDetailsActivity",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ListDAO1311685889[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListDAO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCreate(db: SQLiteDatabase)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onUpgrade(db: SQLiteDatabase, i: int, i1: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProduit165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProduit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProduitDetailsActivity1243990011[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProduitDetailsActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   editText: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   holdTitle: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   index: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   listProduit: ListProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   services: ListServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   textView: TextView [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ sauvegarderListe(view: View)</TD></TR>
<TR><TD ALIGN="LEFT" >+ supprimerListe(view: View)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListRepository886306589[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connexion: ListDAO [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addListe(listProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteListe(listProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getListesProduitByName(name: String): ListProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateTitleList(listProduit: ListProduit, nom: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListServices121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   listProduit: ListProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: ListRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteList(context: Context, ListProduit: ListProduit)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllList(context: Context): List&lt;ListProduit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getListProduitByName(context: Context, title: String): ListProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ miseAJourListProduit(context: Context, ListProduit: ListProduit, title: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ListProduitDetailsActivity1243990011 -> ListProduit165667126[label="listProduit
[0..1]"];
ListProduitDetailsActivity1243990011 -> ListServices121729986[label="services
[0..1]"];
ListRepository886306589 -> ListDAO1311685889[label="connexion
[0..1]"];
ListServices121729986 -> ListProduit165667126[label="listProduit
[0..1]"];
ListServices121729986 -> ListRepository886306589[label="repository
[0..1]"];
    
}
@enduml