@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "nc.unc.ktrochon.pocketlist.MainActivity#onClick(View)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.MainActivity",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_360274715 { 
   	label=MainActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   MainActivity1243990011XXXajouterListe2666181[
	label="+ ajouterListe()"
	style=filled
	fillcolor=white
	tooltip="MainActivity

null"
	fontcolor=darkgreen
];

MainActivity1243990011XXXhasChecked2666181[
	label="+ hasChecked()"
	style=filled
	fillcolor=white
	tooltip="MainActivity

null"
	fontcolor=darkgreen
];

MainActivity1243990011XXXonClick2666181[
	label="+ onClick()"
	style=filled
	fillcolor=white
	tooltip="MainActivity

null"
	penwidth=4
	fontcolor=darkgreen
];

MainActivity1243990011XXXshowListDetail104431[
	label="+ showListDetail()"
	style=filled
	fillcolor=white
	tooltip="MainActivity

null"
	fontcolor=darkgreen
];

MainActivity1243990011XXXshowProduitDetail104431[
	label="+ showProduitDetail()"
	style=filled
	fillcolor=white
	tooltip="MainActivity

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
MainActivity1243990011XXXonClick2666181 -> MainActivity1243990011XXXajouterListe2666181;
MainActivity1243990011XXXonClick2666181 -> MainActivity1243990011XXXhasChecked2666181;
MainActivity1243990011XXXonClick2666181 -> MainActivity1243990011XXXshowListDetail104431;
MainActivity1243990011XXXonClick2666181 -> MainActivity1243990011XXXshowProduitDetail104431;
    
}
@enduml