@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.entity.CategoryProduit",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CategoryProduit165667126[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryProduit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   categoryId: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryName: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CategoryServices121729986[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CategoryServices</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   categoryProduit: CategoryProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: CategoryRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getAllCategory(context: Context): List&lt;CategoryProduit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCategoryById(context: Context, id: int): CategoryProduit</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCategoryProduitByName(context: Context, categoryName: String): CategoryProduit</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DetailsProduitActivity1243990011[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DetailsProduitActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   appartenirService: AppartenirService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   category: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryProduit: CategoryProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   description: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   descriptionView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listServices: ListServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   nomProduitView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produit: Produit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produitIndex: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produitServices: ProduitServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   quantity: EditText [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   quantityView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   services: CategoryServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   title: EditText [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ sauvegarderProduit(view: View)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListProduitActivity1243990011[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListProduitActivity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   adapter: ProduitAdapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   appartenir: List&lt;Appartenir&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   category: List&lt;CategoryProduit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   caterogyServices: CategoryServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listProduit: ListProduit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listServices: ListServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produitServices: ProduitServices [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produits: List&lt;Produit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   services: AppartenirService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onClick(view: View)</TD></TR>
<TR><TD ALIGN="LEFT" ># onCreate(savedInstanceState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ showNoteDetail(produitIndex: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ProduitAdapter1282035804[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProduitAdapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   appartenirs: List&lt;Appartenir&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   categoryProduits: List&lt;CategoryProduit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   itemClickListener: OnClickListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   produits: List&lt;Produit&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(holder: ViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(parent: ViewGroup, viewType: int): ViewHolder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
CategoryServices121729986 -> CategoryProduit165667126[label="categoryProduit
[0..1]"];
DetailsProduitActivity1243990011 -> CategoryProduit165667126[label="categoryProduit
[0..1]"];
DetailsProduitActivity1243990011 -> CategoryServices121729986[label="services
[0..1]"];
ListProduitActivity1243990011 -> CategoryProduit165667126[label="category
[0..*]"];
ListProduitActivity1243990011 -> CategoryServices121729986[label="caterogyServices
[0..1]"];
ListProduitActivity1243990011 -> ProduitAdapter1282035804[label="adapter
[0..1]"];
ProduitAdapter1282035804 -> CategoryProduit165667126[label="categoryProduits
[0..*]"];
    
}
@enduml