@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "nc.unc.ktrochon.pocketlist.entity.Produit#getNomProduit()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "nc.unc.ktrochon.pocketlist.entity.Produit",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_115946 { 
   	label=unc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_949228562 { 
   	label=ktrochon
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1943718057 { 
   	label=DetailsProduitActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   DetailsProduitActivity1243990011XXXsauvegarderProduit2666181[
	label="+ sauvegarderProduit()"
	style=filled
	fillcolor=white
	tooltip="DetailsProduitActivity

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_485632203 { 
   	label=AddProduitAdapter
	labeljust=l
	fillcolor=white
	style=filled
   
   AddProduitAdapter1282035804XXXonBindViewHolder298551242[
	label="+ onBindViewHolder()"
	style=filled
	fillcolor=white
	tooltip="AddProduitAdapter

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_572178641 { 
   	label=Produit
	labeljust=l
	fillcolor=white
	style=filled
   
   Produit165667126XXXgetNomProduit0[
	label="+ getNomProduit()"
	style=filled
	fillcolor=white
	tooltip="Produit

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_774926626 { 
   	label=ProduitRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   ProduitRepository886306589XXXaddProduit1355179401[
	label="+ addProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];

ProduitRepository886306589XXXdeleteProduit1355179401[
	label="+ deleteProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];

ProduitRepository886306589XXXupdateDescriptionProduit1897515218[
	label="+ updateDescriptionProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];

ProduitRepository886306589XXXupdateNomProduit1897515218[
	label="+ updateNomProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_824656552 { 
   	label=ProduitAdapter
	labeljust=l
	fillcolor=white
	style=filled
   
   ProduitAdapter1282035804XXXonBindViewHolder298551242[
	label="+ onBindViewHolder()"
	style=filled
	fillcolor=white
	tooltip="ProduitAdapter

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_908840667 { 
   	label=ProduitServices
	labeljust=l
	fillcolor=white
	style=filled
   
   ProduitServices121729986XXXaddProduit1849432294[
	label="+ addProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];

ProduitServices121729986XXXdeleteProduit1849432294[
	label="+ deleteProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];

ProduitServices121729986XXXmiseAJourNomProduit500514187[
	label="+ miseAJourNomProduit()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];

ProduitServices121729986XXXupdateDescriptionProduct500514187[
	label="+ updateDescriptionProduct()"
	style=filled
	fillcolor=white
	tooltip="ProduitServices

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AddProduitAdapter1282035804XXXonBindViewHolder298551242 -> Produit165667126XXXgetNomProduit0;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> Produit165667126XXXgetNomProduit0;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ProduitServices121729986XXXaddProduit1849432294;
DetailsProduitActivity1243990011XXXsauvegarderProduit2666181 -> ProduitServices121729986XXXmiseAJourNomProduit500514187;
ProduitAdapter1282035804XXXonBindViewHolder298551242 -> Produit165667126XXXgetNomProduit0;
ProduitRepository886306589XXXaddProduit1355179401 -> Produit165667126XXXgetNomProduit0;
ProduitRepository886306589XXXdeleteProduit1355179401 -> Produit165667126XXXgetNomProduit0;
ProduitRepository886306589XXXupdateDescriptionProduit1897515218 -> Produit165667126XXXgetNomProduit0;
ProduitRepository886306589XXXupdateNomProduit1897515218 -> Produit165667126XXXgetNomProduit0;
ProduitServices121729986XXXaddProduit1849432294 -> ProduitRepository886306589XXXaddProduit1355179401;
ProduitServices121729986XXXdeleteProduit1849432294 -> ProduitRepository886306589XXXdeleteProduit1355179401;
ProduitServices121729986XXXmiseAJourNomProduit500514187 -> ProduitRepository886306589XXXupdateNomProduit1897515218;
ProduitServices121729986XXXupdateDescriptionProduct500514187 -> ProduitRepository886306589XXXupdateDescriptionProduit1897515218;
    
}
@enduml